apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flipop
  name: flipop
  namespace: flipop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flipop
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flipop
    spec:
      containers:
      - env:
        - name: DIGITALOCEAN_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: DIGITALOCEAN_ACCESS_TOKEN
              name: flipop
        # use fixed tag instead of latest
        image: digitaloceanapps/flipop:8c2ae5a # release from 09.05.2025
        imagePullPolicy: IfNotPresent
        name: flipop
        ports:
        - containerPort: 8080
          name: prometheus
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: flipop
      serviceAccountName: flipop
      terminationGracePeriodSeconds: 30
